name = "greenlink-shortener"
main = "src/index.js"
compatibility_date = "2025-08-04"

# KV namespace for storing URL mappings
[[kv_namespaces]]
binding = "URL_STORE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# Environment variables
[vars]
DOMAIN = "yourdomain.com"
ADMIN_PASSWORD = "your-password"  # Change this to a secure password
