name = "greenlink-shortener"
main = "src/index.js"
compatibility_date = "2025-08-04"

# KV namespace for storing URL mappings
[[kv_namespaces]]
binding = "URL_STORE"
id = "7b589339745a46738dde6da7aff3cc92"
preview_id = "your-preview-kv-namespace-id"

# Environment variables
[vars]
DOMAIN = "gl1.qzz.io"
ADMIN_PASSWORD = "wzg@0204"  # Change this to a secure password
